---
title: "April's Website"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
Hello everyone, my name is Ma Yao. I am currently a full-time graduate student at Boston University. I received my bachelor's degree in mathematics from Durham University in the UK.

I am a rigorous and rational person. I am used to looking for answers from data and structure. I like to deeply understand the logic behind things rather than staying on the surface. Whether I am studying simulation modeling, financial analysis, or processing data with Python and R, I tend to pursue accuracy and clarity of methods. I usually pay attention to organization in my work, efficiency in communication, and I respect the collaborative atmosphere in the team.

In addition to studying and working, I currently live in Boston and have a gentle and very cute Maine Coon cat, which is also an important companion in my life.

I hope to communicate with you more and learn from each other in the future. Thank you!